### ISSUE TITLE
Remove DB Archive from Agency modules

### ISSUE THREAD

**Issue by dwaring87** [right-track/right-track-db-build#9]
Remove archived right track databases from each of the agency modules.  The complete archive makes the agency modules too large.

- [x] Remove archived databases from each agency module.
    - [x] clean right-track-agency-mnr (right-track/right-track-agency-mnr#1)
    - [x] clean right-track-agency-lirr (right-track/right-track-agency-lirr#1)
- [x] Update the db-build install script to no longer create the archive
- [x] Add archived databases to shared google drive folder
- [x] Update db-build post-install script to upload newly compiled database to google drive folder
- [x] Update right-track-server endpoint for retrieving list of archived databases and downloading an archived database (right-track/right-track-server#9)
